version: "3.5"
# You should be able to find & replace all instances of mattermost with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  mattermost:
  mattermost-private:

volumes:
  mattermost_config:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client_plugins:
  mattermost-db:

secrets:
  mattermost_admin_password:
    name: ${STACK_NAME:-technocore}_mattermost_admin_password
    external: true
  mattermost_mattermost_db_password:
    name: ${STACK_NAME:-technocore}_mattermost_mattermost_db_password
    external: true
  mattermost_db_mattermost_password:
    name: ${STACK_NAME:-technocore}_mattermost_db_mattermost_password
    external: true

services:
  ingress:
    networks:
      - mattermost

  mattermost:
    deploy:
      labels:
        - traefik.frontend.rule=$MATTERMOST_ROUTING_LABEL
        - traefik.frontend.priority=$MATTERMOST_ROUTING_LABEL_PRIORITY
        # You'll need to set applicaiton's port here.
        - traefik.port=8065
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_mattermost
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      #- MQTT_USER=${mattermost}
      #- ADMIN_USER=${ADMIN_USER}
      # set same as db credentials and dbname
      - DB_HOST=mattermost_db
      - DB_PORT_NUMBER=5432
      - MM_USERNAME=mattermost
      - MM_PASSWORD={{"{{DOCKER-SECRET:mattermost_db_password}}"}}
      - MM_DBNAME=mattermost
      - "MM_SERVICESETTINGS_SITEURL=https://mattermost.${DOMAIN}"
      - MM_SERVICESETTINGS_ENABLECUSTOMEMOJI=true
      - MM_SERVICESETTINGS_ENABLEEMAILINVITATIONS=true
      - MM_SERVICESETTINGS_ENABLEGIF_PICKER=true
      - MM_EMAILSETTINGS_SMTPSERVER=smtp_relay
      - MM_EMAILSETTINGS_SMTPPORT=587
      - MM_TEAMSETTINGS_ENABLEOPENSERVER=true
      - MM_LOGSETTINGS_ENABLEFILE=false
      - MM_EMAILSETTINGS_REQUIREEMAIL_VERIFICATION=true
      - MM_EMAILSETTINGS_FEEDBACKEMAIL=${TECHNOCORE_SMTP_ADDRESS}
      - MM_EMAILSETTINGS_REPLYTOADDRESS=${TECHNOCORE_SMTP_ADDRESS}
      - MM_DISPLAYSETTINGS_EXPERIMENTALTIMEZONE=true
    image: ${image_provider:-scififarms}/technocore-mattermost:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - mattermost
      - mattermost-private
    secrets:
      - source: mattermost_mattermost_db_password
        target: mattermost_db_password
    volumes:
      - mattermost_config:/mattermost/config:rw
      - mattermost_data:/mattermost/data:rw
      - mattermost_logs:/mattermost/logs:rw
      - mattermost_plugins:/mattermost/plugins:rw
      - mattermost_client_plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      - ${DEV_MOUNT_MATTERMOST_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  mattermost_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD={{"{{DOCKER-SECRET:mattermost_password}}"}}
      - POSTGRES_DB=mattermost
    image: ${image_provider:-scififarms}/technocore-mattermost-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - mattermost-private
    secrets:
      - source: mattermost_db_mattermost_password
        target: mattermost_password
    volumes:
      - mattermost-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
