version: "3.5"
# You should be able to find & replace all instances of mattermost with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  mattermost:
  mattermost-private:

volumes:
  mattermost:
  mattermost-db:

secrets:
  mattermost_admin_password:
    name: ${STACK_NAME:-technocore}_mattermost_admin_password
    external: true
  mattermost_mattermost_db_password:
    name: ${STACK_NAME:-technocore}_mattermost_mattermost_db_password
    external: true
  mattermost_db_mattermost_password:
    name: ${STACK_NAME:-technocore}_mattermost_db_mattermost_password
    external: true

services:
  ingress:
    networks:
      - mattermost

  mattermost:
    deploy:
      labels:
        - traefik.frontend.rule=$MATTERMOST_ROUTING_LABEL
        - traefik.frontend.priority=$MATTERMOST_ROUTING_LABEL_PRIORITY
        # You'll need to set applicaiton's port here.
        - traefik.port=SET_ME_PLEASE
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_mattermost
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      #- MQTT_USER=${mattermost}
      - ADMIN_USER=${ADMIN_USER}
    image: ${image_provider:-scififarms}/technocore-mattermost:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - mattermost
      - mattermost-private
    secrets:
      - source: mattermost_mattermost_db_password
        target: mattermost_db_password
    volumes:
      # Likely need to change this
      - mattermost:/var/lib/mattermost
      - ${DEV_MOUNT_MATTERMOST_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  mattermost_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    #environment:
    image: ${image_provider:-scififarms}/technocore-mattermost-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - mattermost-private
    secrets:
      - source: mattermost_db_admin_password
        target: admin_password
      - source: mattermost_db_mattermost_password
        target: mattermost_password
    volumes:
      # Likely need to change this
      - mattermost-db:/var/lib/mattermost
